version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    assignees:
      - markphelps
    labels:
      - "dependencies"
      - "github_actions"
      # kodiak `merge.automerge_label`
      - "automerge"
    groups:
      github-actions:
        patterns: ["*"]
