apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "flipt.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
  labels:
    {{- include "flipt.labels" . | nindent 4 }}
data:
  default.yml: |
    {{ toYaml .Values.flipt.config | nindent 4 }}
