{{- if (.Values.migration).enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "flipt.migration_name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flipt.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  activeDeadlineSeconds: {{ .Values.migration.deadLine }}
  backoffLimit: 0
  template:
    metadata:
      annotations: {{- include "common.classes.podAnnotations" . | nindent 8 }}
      labels:
        {{- include "flipt.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "flipt.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
          - "./flipt"
          - "migrate"
          env:
            - name: FLIPT_META_STATE_DIRECTORY
              value: /home/flipt/.config/flipt
            {{- if .Values.flipt.extraEnvVars }}
            {{- include "common.tplvalues.render" (dict "value" .Values.flipt.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          {{- if .Values.flipt.envFrom }}
          envFrom:
            {{- toYaml .Values.flipt.envFrom | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: flipt-config
              mountPath: /etc/flipt/config/default.yml
              readOnly: true
              subPath: default.yml
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: flipt-local-state
          emptyDir: {}
        - name: flipt-config
          configMap:
            name: {{ include "flipt.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{ end -}}
